---
apiVersion: generic.vault.jet.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: example
spec:
  forProvider:
    path: "secret/foo"
    dataJsonSecretRef:
      key: data_json
      name: example-datajson
      namespace: default

---
apiVersion: v1
kind: Secret
metadata:
  name: example-datajson
  namespace: default
stringData:
  data_json: |
      {
        "foo": "bar",
        "pizza": "cheese"
      }
type: Opaque

---
apiVersion: generic.vault.jet.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: example-non-json
spec:
  forProvider:
    path: "secret/fizz"
    stringDataSecretRef:
      key: fizz
      name: example-data
      namespace: default

---
apiVersion: v1
kind: Secret
metadata:
  name: example-data
  namespace: default
stringData:
  fizz: buzz
  pizza: hawaiian
type: Opaque